-- =============================================================
-- Migración: Presupuestos
-- Ejecutar UNA vez en Supabase -> SQL Editor -> Run
-- =============================================================

create table if not exists public.budgets (
  id           uuid primary key default gen_random_uuid(),
  number       bigint generated by default as identity,
  patient_id   uuid not null references public.patients(id) on delete cascade,
  description  text not null,
  budget_date  date default current_date,
  created_at   timestamptz not null default now(),
  created_by   uuid references auth.users(id) default auth.uid()
);
create index if not exists budgets_patient_idx on public.budgets (patient_id);

create table if not exists public.budget_items (
  id           uuid primary key default gen_random_uuid(),
  budget_id    uuid not null references public.budgets(id) on delete cascade,
  procedure_id uuid references public.procedures(id) on delete set null,
  code         text,
  name         text not null,
  teeth        text,
  quantity     integer not null default 1,
  unit_price   numeric(12,2) not null default 0,
  done_count   integer not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists budget_items_budget_idx on public.budget_items (budget_id);

-- Un pago de la cuenta puede imputarse a un presupuesto ("a cuenta de …")
alter table public.account_entries
  add column if not exists budget_id uuid references public.budgets(id) on delete set null;

alter table public.budgets      enable row level security;
alter table public.budget_items enable row level security;

do $$
declare t text;
begin
  foreach t in array array['budgets','budget_items']
  loop
    execute format('drop policy if exists "authenticated full access" on public.%I;', t);
    execute format(
      'create policy "authenticated full access" on public.%I
         for all to authenticated using (true) with check (true);', t);
  end loop;
end $$;
